# Generated by Django 5.2.14 on 2026-07-24 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'جاري المعالجة'), ('completed', 'مكتمل'), ('error', 'خطأ')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'ملف مرفوع',
                'verbose_name_plural': 'ملفات مرفوعة',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField(default=dict)),
                ('column_types', models.JSONField(default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('col_count', models.PositiveIntegerField(default=0)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analyzer.uploadedfile')),
            ],
            options={
                'verbose_name': 'نتيجة التحليل',
                'verbose_name_plural': 'نتائج التحليل',
            },
        ),
    ]
