# Generated by Django 5.2.14 on 2026-07-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='analysis_mode',
            field=models.CharField(choices=[('auto', 'تحليل تلقائي'), ('custom', 'تحليل مخصص')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='custom_query',
            field=models.TextField(blank=True, default=''),
        ),
    ]
